# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk11

# Build script
script:
  - mvn -f spring-graphql-api/pom.xml -Dtravis=true install

# Improve the build speed for future builds
cache:
  directories:
  - $HOME/.m2

# Speed up build
sudo: false

# Ubuntu trusty server
# Apparently it's the quickest out of the linux os
dist: trusty
