# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk11

# Build script
script:
  - mvn -f spring-graphql-api/pom.xml install
  - mvn -f spring-graphql-api/pom.xml test

# Improve the build speed for future builds
cache:
  directories:
  - $HOME/.m2

before_install:
  java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:~/jooq -script spring-graphql-api/src/main/resource/h2schema/schema.sql
